//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int id { get; set; }
        public string InstaHandle { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public int Adult { get; set; }
        public int Gender { get; set; }
        public string EyeColor { get; set; }
        public string SkinColor { get; set; }
        public string HairColor { get; set; }
        public string City { get; set; }
        public string Comments { get; set; }
    }
}
